

openapi: 3.0.0
info:
  title: 用户 API
  version: 0.0.7
  description: |
    这是一个用于用户管理的 API。通过该 API，您可以注册、更新、删除用户，并查询用户信息。
    该文档提供了所有可用接口的详细说明。
  contact:
    name: 开发者支持
    email: support@example.com
tags:
  - name: user
    description: 用户方面接口
  - name: wlt
    description: 钱包方面接口
  - name: YLwlt
    description: 盈利钱包方面接口



components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: uname
parameters:
  - in: cookie
    name: uname
    required: true
    schema:
      type: string
      default: "007"
paths:
  /login:
    get:
      tags:
        - user
      summary: "登录用户的方法"
      description: " "

      parameters:
        - name: uname
          in: query
          description: "用户名"
          required: true
          schema:
            type: string
        - name: pwd
          in: query
          description: "密码"
          required: true
          schema:
            type: string

      responses:
        "200":
          description: "登录成功"
          content:
            text/plain:
              schema:
                type: string
                example: "ok"
        "500":
          description: 登录失败"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errcode:
                    type: string
                    example: "user pwd err"
                  errmsg:
                    type: string
                    example: "错误用户名"
  /reg:
    get:
      tags:
        - user
      summary: "注册用户的方法reg"
      description: "注册用户的方法dscrp。。。。"
      operationId: "registerUser"
      parameters:
        - name: uname
          in: query
          description: "用户名"
          required: true
          schema:
            type: string
        - name: pwd
          in: query
          description: "密码"
          required: true
          schema:
            type: string
        - name: invtr
          in: query
          description: "邀请人"
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "注册成功"
          content:
            text/plain:
              schema:
                type: string
                example: "ok"
        "500":
          description: "注册失败"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errcode:
                    type: string
                    example: "user exist"
                  errmsg:
                    type: string
                    example: "重复用户名"
        "201":
          description: "注册成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "注册成功"
  /users:

    get:
      tags:
        - user
      summary: 获取所有用户
      responses:
        '200':
          description: 用户列表
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /Trans:
    get:
      summary: 转账操作
      description: 进行转账操作
      tags:
        - wlt 钱包方面接口
      parameters:
        - name: uname
          in: cookie
          required: true
          description: 用户名（存储于 Cookie 中）
          schema:
            type: string
        - name: changeAmount
          in: query
          required: true
          description: 转账金额
          schema:
            type: number
      responses:
        "200":
          description: 转账成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 转账成功
        "400":
          description: 参数错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 无效的转账金额
      examples:
        example-1:
          summary: 示例调用
          description: 以 `changeAmount=8` 进行调用
          value: "/Trans?changeAmount=8"
  /CompleteChargeHdr:
    get:
      tags:
        - "wlt 钱包方面接口"
      summary: "完成充值订单"
      description: "根据订单 ID 完成充值操作"
      parameters:
        - name: "id"
          in: "query"
          required: true
          schema:
            type: "string"
            example: "ORD123456"
          description: "订单 ID (ordid)"
      responses:
        "200":
          description: "充值订单完成"
          content:
            application/json:
              schema:
                type: "object"
        "400":
          description: "请求参数错误"
        "404":
          description: "订单未找到"
        "500":
          description: "服务器内部错误"

  /RechargeHdr:
    get:
      components:
        securitySchemes:
          cookieAuth:
            type: apiKey
            in: cookie
            name: uname

      security:
        - cookieAuth: [ ]
      tags:
        - wlt 钱包方面接口
      summary:   recharge
      description: This endpoint retrieves recharge header information based on the provided amount and username.
      parameters:
        - in: query
          name: amt
          required: true
          schema:
            type: integer
            example: 888
          description: The amount to be recharged.
        - in: cookie
          name: uname
          required: true
          schema:
            type: string
            default: "007"
          description: The username for the request.
      responses:
        '200':
          description: Successful response with recharge details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      rechargeId:
                        type: integer
                        example: 12345
                      amount:
                        type: integer
                        example: 888

        '500':
          description: Internal server error.
  /BetHdr:
    get:
      tags:
        - bet
      summary: 投注
      description: ""
      operationId: getBet
      parameters:
        - name: bettxt
          in: query
          required: true
          description: "投注内容"
          schema:
            type: string
            example: "123"
        - name: uname
          in: cookie
          required: true
          description: 用户名（从 Cookie 获取）
          schema:
            type: string
      responses:
        '200':
          description: 成功响应
        '400':
          description: 错误请求